import { Header } from '../../../Shared/components/Header/Header';
import '../../../style/scss/style.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Заказы | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function userOrdersLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className='body'>
                <Header />
                <div className='main'>{children}</div>
            </div>
        </>
    );
}
