import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

const nunito = Nunito({
    variable: '--font-Nunito',
    subsets: ['latin'],
});

// export const metadata: Metadata = {
//     title: 'Главная | PIZZA PRO',
//     description: 'Generated by create next app',
// };

export default function OrderLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <div className='body'>{children}</div>
        </div>
    );
}
