import '../../../style/scss/style.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Оформление заказа | PIZZA PRO',
    description: 'Generated by create next app',
};

export default function OrderLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className='body'>{children}</div>
        </>
    );
}
